name: Run Tests

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run tests
        run: make test

      - name: Run e2e tests in ethermint with current branch
        if: github.event_name == 'pull_request'
        shell: bash
        env:
          SECRET_TOKEN: ${{ secrets.CONCRETE_ACTIONS_TOKEN }}
        run: |
          curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $SECRET_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/zama-ai/zbc-ethermint/actions/workflows/run-ci-e2e-test.yml/dispatches \
          -d '{"ref":"main","inputs":{"fhevm_go_commit":"${{ github.event.pull_request.head.sha }}"}}'
